//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  update: Update;
  updateConnection: UpdateConnection;
  post: Post;
  postConnection: PostConnection;
  project: Project;
  projectConnection: ProjectConnection;
  baseline: Baseline;
  baselineConnection: BaselineConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUpdateArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryUpdateConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UpdateFilter>;
};


export type QueryPostArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPostConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryBaselineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBaselineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BaselineFilter>;
};

export type DocumentFilter = {
  update?: InputMaybe<UpdateFilter>;
  post?: InputMaybe<PostFilter>;
  project?: InputMaybe<ProjectFilter>;
  baseline?: InputMaybe<BaselineFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Update | Post | Project | Baseline | Folder;

export type Update = Node & Document & {
  __typename?: 'Update';
  title: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  publishedDate: Scalars['String']['output'];
  published?: Maybe<Scalars['Boolean']['output']>;
  category: Scalars['String']['output'];
  featuredImage?: Maybe<Scalars['String']['output']>;
  imageAlt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  showInAnnouncementBar?: Maybe<Scalars['Boolean']['output']>;
  announcementText?: Maybe<Scalars['String']['output']>;
  announcementLinkLabel?: Maybe<Scalars['String']['output']>;
  announcementStart?: Maybe<Scalars['String']['output']>;
  announcementEnd?: Maybe<Scalars['String']['output']>;
  announcementPriority?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type UpdateFilter = {
  title?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  publishedDate?: InputMaybe<DatetimeFilter>;
  published?: InputMaybe<BooleanFilter>;
  category?: InputMaybe<StringFilter>;
  featuredImage?: InputMaybe<ImageFilter>;
  imageAlt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
  showInAnnouncementBar?: InputMaybe<BooleanFilter>;
  announcementText?: InputMaybe<StringFilter>;
  announcementLinkLabel?: InputMaybe<StringFilter>;
  announcementStart?: InputMaybe<DatetimeFilter>;
  announcementEnd?: InputMaybe<DatetimeFilter>;
  announcementPriority?: InputMaybe<NumberFilter>;
};

export type UpdateConnectionEdges = {
  __typename?: 'UpdateConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Update>;
};

export type UpdateConnection = Connection & {
  __typename?: 'UpdateConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<UpdateConnectionEdges>>>;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PostFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PostConnectionEdges = {
  __typename?: 'PostConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Post>;
};

export type PostConnection = Connection & {
  __typename?: 'PostConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PostConnectionEdges>>>;
};

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  projectType?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  pillars?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  criteria?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  rating?: Maybe<Scalars['String']['output']>;
  score?: Maybe<Scalars['Float']['output']>;
  relatedBaselines?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  published?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  location?: InputMaybe<StringFilter>;
  projectType?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<ImageFilter>;
  pillars?: InputMaybe<StringFilter>;
  criteria?: InputMaybe<StringFilter>;
  rating?: InputMaybe<StringFilter>;
  score?: InputMaybe<NumberFilter>;
  relatedBaselines?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type BaselineSources = {
  __typename?: 'BaselineSources';
  label?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Baseline = Node & Document & {
  __typename?: 'Baseline';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  projectType?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  region?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  coverImage?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  pillars?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  criteria?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  sdgs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  rating?: Maybe<Scalars['String']['output']>;
  estimatedCarbonKg?: Maybe<Scalars['Float']['output']>;
  estimatedWasteKg?: Maybe<Scalars['Float']['output']>;
  estimatedLifespanUses?: Maybe<Scalars['Float']['output']>;
  recyclability?: Maybe<Scalars['String']['output']>;
  productionAssumptions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  materialAssumptions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  transportAssumptions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  disposalAssumptions?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  evidenceNotes?: Maybe<Scalars['String']['output']>;
  sources?: Maybe<Array<Maybe<BaselineSources>>>;
  relatedProjects?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  published?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BaselineSourcesFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type BaselineFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  projectType?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  gallery?: InputMaybe<ImageFilter>;
  pillars?: InputMaybe<StringFilter>;
  criteria?: InputMaybe<StringFilter>;
  sdgs?: InputMaybe<StringFilter>;
  rating?: InputMaybe<StringFilter>;
  estimatedCarbonKg?: InputMaybe<NumberFilter>;
  estimatedWasteKg?: InputMaybe<NumberFilter>;
  estimatedLifespanUses?: InputMaybe<NumberFilter>;
  recyclability?: InputMaybe<StringFilter>;
  productionAssumptions?: InputMaybe<StringFilter>;
  materialAssumptions?: InputMaybe<StringFilter>;
  transportAssumptions?: InputMaybe<StringFilter>;
  disposalAssumptions?: InputMaybe<StringFilter>;
  evidenceNotes?: InputMaybe<StringFilter>;
  sources?: InputMaybe<BaselineSourcesFilter>;
  relatedProjects?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BaselineConnectionEdges = {
  __typename?: 'BaselineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Baseline>;
};

export type BaselineConnection = Connection & {
  __typename?: 'BaselineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BaselineConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateUpdate: Update;
  createUpdate: Update;
  updatePost: Post;
  createPost: Post;
  updateProject: Project;
  createProject: Project;
  updateBaseline: Baseline;
  createBaseline: Baseline;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateUpdateArgs = {
  relativePath: Scalars['String']['input'];
  params: UpdateMutation;
};


export type MutationCreateUpdateArgs = {
  relativePath: Scalars['String']['input'];
  params: UpdateMutation;
};


export type MutationUpdatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationCreatePostArgs = {
  relativePath: Scalars['String']['input'];
  params: PostMutation;
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateBaselineArgs = {
  relativePath: Scalars['String']['input'];
  params: BaselineMutation;
};


export type MutationCreateBaselineArgs = {
  relativePath: Scalars['String']['input'];
  params: BaselineMutation;
};

export type DocumentUpdateMutation = {
  update?: InputMaybe<UpdateMutation>;
  post?: InputMaybe<PostMutation>;
  project?: InputMaybe<ProjectMutation>;
  baseline?: InputMaybe<BaselineMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  update?: InputMaybe<UpdateMutation>;
  post?: InputMaybe<PostMutation>;
  project?: InputMaybe<ProjectMutation>;
  baseline?: InputMaybe<BaselineMutation>;
};

export type UpdateMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  publishedDate?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  featuredImage?: InputMaybe<Scalars['String']['input']>;
  imageAlt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  showInAnnouncementBar?: InputMaybe<Scalars['Boolean']['input']>;
  announcementText?: InputMaybe<Scalars['String']['input']>;
  announcementLinkLabel?: InputMaybe<Scalars['String']['input']>;
  announcementStart?: InputMaybe<Scalars['String']['input']>;
  announcementEnd?: InputMaybe<Scalars['String']['input']>;
  announcementPriority?: InputMaybe<Scalars['Float']['input']>;
};

export type PostMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  projectType?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  pillars?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  criteria?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  rating?: InputMaybe<Scalars['String']['input']>;
  score?: InputMaybe<Scalars['Float']['input']>;
  relatedBaselines?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type BaselineSourcesMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type BaselineMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  projectType?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  pillars?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  criteria?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  sdgs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  rating?: InputMaybe<Scalars['String']['input']>;
  estimatedCarbonKg?: InputMaybe<Scalars['Float']['input']>;
  estimatedWasteKg?: InputMaybe<Scalars['Float']['input']>;
  estimatedLifespanUses?: InputMaybe<Scalars['Float']['input']>;
  recyclability?: InputMaybe<Scalars['String']['input']>;
  productionAssumptions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  materialAssumptions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  transportAssumptions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  disposalAssumptions?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  evidenceNotes?: InputMaybe<Scalars['String']['input']>;
  sources?: InputMaybe<Array<InputMaybe<BaselineSourcesMutation>>>;
  relatedProjects?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type UpdatePartsFragment = { __typename: 'Update', title: string, summary?: string | null, publishedDate: string, published?: boolean | null, category: string, featuredImage?: string | null, imageAlt?: string | null, body?: any | null, showInAnnouncementBar?: boolean | null, announcementText?: string | null, announcementLinkLabel?: string | null, announcementStart?: string | null, announcementEnd?: string | null, announcementPriority?: number | null };

export type PostPartsFragment = { __typename: 'Post', title: string, body?: any | null };

export type ProjectPartsFragment = { __typename: 'Project', title: string, description?: string | null, year?: number | null, location?: string | null, projectType?: string | null, website?: string | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, rating?: string | null, score?: number | null, relatedBaselines?: Array<string | null> | null, published?: boolean | null, body?: any | null };

export type BaselinePartsFragment = { __typename: 'Baseline', title: string, slug: string, summary?: string | null, projectType?: string | null, format?: string | null, region?: string | null, year?: number | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, sdgs?: Array<string | null> | null, rating?: string | null, estimatedCarbonKg?: number | null, estimatedWasteKg?: number | null, estimatedLifespanUses?: number | null, recyclability?: string | null, productionAssumptions?: Array<string | null> | null, materialAssumptions?: Array<string | null> | null, transportAssumptions?: Array<string | null> | null, disposalAssumptions?: Array<string | null> | null, evidenceNotes?: string | null, relatedProjects?: Array<string | null> | null, published?: boolean | null, body?: any | null, sources?: Array<{ __typename: 'BaselineSources', label?: string | null, url?: string | null } | null> | null };

export type UpdateQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type UpdateQuery = { __typename?: 'Query', update: { __typename: 'Update', id: string, title: string, summary?: string | null, publishedDate: string, published?: boolean | null, category: string, featuredImage?: string | null, imageAlt?: string | null, body?: any | null, showInAnnouncementBar?: boolean | null, announcementText?: string | null, announcementLinkLabel?: string | null, announcementStart?: string | null, announcementEnd?: string | null, announcementPriority?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type UpdateConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<UpdateFilter>;
}>;


export type UpdateConnectionQuery = { __typename?: 'Query', updateConnection: { __typename?: 'UpdateConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'UpdateConnectionEdges', cursor: string, node?: { __typename: 'Update', id: string, title: string, summary?: string | null, publishedDate: string, published?: boolean | null, category: string, featuredImage?: string | null, imageAlt?: string | null, body?: any | null, showInAnnouncementBar?: boolean | null, announcementText?: string | null, announcementLinkLabel?: string | null, announcementStart?: string | null, announcementEnd?: string | null, announcementPriority?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PostQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PostQuery = { __typename?: 'Query', post: { __typename: 'Post', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PostConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PostFilter>;
}>;


export type PostConnectionQuery = { __typename?: 'Query', postConnection: { __typename?: 'PostConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PostConnectionEdges', cursor: string, node?: { __typename: 'Post', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, description?: string | null, year?: number | null, location?: string | null, projectType?: string | null, website?: string | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, rating?: string | null, score?: number | null, relatedBaselines?: Array<string | null> | null, published?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, description?: string | null, year?: number | null, location?: string | null, projectType?: string | null, website?: string | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, rating?: string | null, score?: number | null, relatedBaselines?: Array<string | null> | null, published?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BaselineQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BaselineQuery = { __typename?: 'Query', baseline: { __typename: 'Baseline', id: string, title: string, slug: string, summary?: string | null, projectType?: string | null, format?: string | null, region?: string | null, year?: number | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, sdgs?: Array<string | null> | null, rating?: string | null, estimatedCarbonKg?: number | null, estimatedWasteKg?: number | null, estimatedLifespanUses?: number | null, recyclability?: string | null, productionAssumptions?: Array<string | null> | null, materialAssumptions?: Array<string | null> | null, transportAssumptions?: Array<string | null> | null, disposalAssumptions?: Array<string | null> | null, evidenceNotes?: string | null, relatedProjects?: Array<string | null> | null, published?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sources?: Array<{ __typename: 'BaselineSources', label?: string | null, url?: string | null } | null> | null } };

export type BaselineConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BaselineFilter>;
}>;


export type BaselineConnectionQuery = { __typename?: 'Query', baselineConnection: { __typename?: 'BaselineConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BaselineConnectionEdges', cursor: string, node?: { __typename: 'Baseline', id: string, title: string, slug: string, summary?: string | null, projectType?: string | null, format?: string | null, region?: string | null, year?: number | null, coverImage?: string | null, gallery?: Array<string | null> | null, pillars?: Array<string | null> | null, criteria?: Array<string | null> | null, sdgs?: Array<string | null> | null, rating?: string | null, estimatedCarbonKg?: number | null, estimatedWasteKg?: number | null, estimatedLifespanUses?: number | null, recyclability?: string | null, productionAssumptions?: Array<string | null> | null, materialAssumptions?: Array<string | null> | null, transportAssumptions?: Array<string | null> | null, disposalAssumptions?: Array<string | null> | null, evidenceNotes?: string | null, relatedProjects?: Array<string | null> | null, published?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sources?: Array<{ __typename: 'BaselineSources', label?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export const UpdatePartsFragmentDoc = gql`
    fragment UpdateParts on Update {
  __typename
  title
  summary
  publishedDate
  published
  category
  featuredImage
  imageAlt
  body
  showInAnnouncementBar
  announcementText
  announcementLinkLabel
  announcementStart
  announcementEnd
  announcementPriority
}
    `;
export const PostPartsFragmentDoc = gql`
    fragment PostParts on Post {
  __typename
  title
  body
}
    `;
export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  description
  year
  location
  projectType
  website
  coverImage
  gallery
  pillars
  criteria
  rating
  score
  relatedBaselines
  published
  body
}
    `;
export const BaselinePartsFragmentDoc = gql`
    fragment BaselineParts on Baseline {
  __typename
  title
  slug
  summary
  projectType
  format
  region
  year
  coverImage
  gallery
  pillars
  criteria
  sdgs
  rating
  estimatedCarbonKg
  estimatedWasteKg
  estimatedLifespanUses
  recyclability
  productionAssumptions
  materialAssumptions
  transportAssumptions
  disposalAssumptions
  evidenceNotes
  sources {
    __typename
    label
    url
  }
  relatedProjects
  published
  body
}
    `;
export const UpdateDocument = gql`
    query update($relativePath: String!) {
  update(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...UpdateParts
  }
}
    ${UpdatePartsFragmentDoc}`;
export const UpdateConnectionDocument = gql`
    query updateConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: UpdateFilter) {
  updateConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...UpdateParts
      }
    }
  }
}
    ${UpdatePartsFragmentDoc}`;
export const PostDocument = gql`
    query post($relativePath: String!) {
  post(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PostParts
  }
}
    ${PostPartsFragmentDoc}`;
export const PostConnectionDocument = gql`
    query postConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PostFilter) {
  postConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PostParts
      }
    }
  }
}
    ${PostPartsFragmentDoc}`;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const BaselineDocument = gql`
    query baseline($relativePath: String!) {
  baseline(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BaselineParts
  }
}
    ${BaselinePartsFragmentDoc}`;
export const BaselineConnectionDocument = gql`
    query baselineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BaselineFilter) {
  baselineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BaselineParts
      }
    }
  }
}
    ${BaselinePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      update(variables: UpdateQueryVariables, options?: C): Promise<{data: UpdateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpdateQueryVariables, query: string}> {
        return requester<{data: UpdateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpdateQueryVariables, query: string}, UpdateQueryVariables>(UpdateDocument, variables, options);
      },
    updateConnection(variables?: UpdateConnectionQueryVariables, options?: C): Promise<{data: UpdateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpdateConnectionQueryVariables, query: string}> {
        return requester<{data: UpdateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: UpdateConnectionQueryVariables, query: string}, UpdateConnectionQueryVariables>(UpdateConnectionDocument, variables, options);
      },
    post(variables: PostQueryVariables, options?: C): Promise<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}> {
        return requester<{data: PostQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostQueryVariables, query: string}, PostQueryVariables>(PostDocument, variables, options);
      },
    postConnection(variables?: PostConnectionQueryVariables, options?: C): Promise<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}> {
        return requester<{data: PostConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PostConnectionQueryVariables, query: string}, PostConnectionQueryVariables>(PostConnectionDocument, variables, options);
      },
    project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    baseline(variables: BaselineQueryVariables, options?: C): Promise<{data: BaselineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BaselineQueryVariables, query: string}> {
        return requester<{data: BaselineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BaselineQueryVariables, query: string}, BaselineQueryVariables>(BaselineDocument, variables, options);
      },
    baselineConnection(variables?: BaselineConnectionQueryVariables, options?: C): Promise<{data: BaselineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BaselineConnectionQueryVariables, query: string}> {
        return requester<{data: BaselineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BaselineConnectionQueryVariables, query: string}, BaselineConnectionQueryVariables>(BaselineConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  