import assert from "node:assert/strict";
import { test } from "node:test";
import { createBlankProject } from "../createProject";
import { addComponent, addCriterionAssessment, addStrategy, duplicateComponent, getComponentRemovalImpact, removeComponent, removeCriterionAssessment, removeStrategy, updateAssessmentScope, updateComponent, updateCriterionAssessment, updateProjectMetadata, updateStrategy } from "./actions";
import { selectAssessmentCount, selectAssessmentsByPillar, selectAssessmentsByStatus, selectComponentCount, selectComponentReferenceCount, selectStrategyCount, selectUnreviewedAssessmentCount } from "./selectors";

const make = () => createBlankProject({ title: "Workspace", id: "workspace", now: new Date("2026-01-01T00:00:00.000Z") });
const later = { now: new Date("2026-02-01T00:00:00.000Z") };
test("metadata updates meaningful content and updatedAt", () => { const project = make(); const next = updateProjectMetadata(project, { title: "Changed" }, later); assert.equal(next.project.title, "Changed"); assert.equal(next.project.updatedAt, later.now.toISOString()); });
test("unchanged metadata preserves updatedAt", () => { const project = make(); assert.equal(updateProjectMetadata(project, { title: project.project.title }, later), project); });
test("component actions preserve stable IDs after rename", () => { let project = addComponent(make(), { name: "Printed cards", type: "print", description: "", notes: "" }, later); const id = project.components[0].id; project = updateComponent(project, id, { name: "Posters" }, later); assert.equal(project.components[0].id, id); project = duplicateComponent(project, id, later); assert.equal(project.components.length, 2); assert.notEqual(project.components[1].id, id); });
test("removes an unreferenced component", () => { const project = addComponent(make(), { name: "One", type: "other", description: "", notes: "" }); assert.equal(removeComponent(project, project.components[0].id, "remove-assessments").components.length, 0); });
test("removes one reference and preserves multi-component assessment", () => { let project = addComponent(make(), { name: "One", type: "other", description: "", notes: "" }); project = addComponent(project, { name: "Two", type: "other", description: "", notes: "" }); project = addCriterionAssessment(project, "E1"); project = updateAssessmentScope(project, "E1", { level: "component", componentIds: project.components.map((item) => item.id) }); const next = removeComponent(project, project.components[0].id, "remove-assessments"); assert.deepEqual(next.criteriaAssessments[0].scope.componentIds, [project.components[1].id]); });
test("reports and safely resolves an orphaned assessment", () => { let project = addComponent(make(), { name: "One", type: "other", description: "", notes: "" }); project = addCriterionAssessment(project, "E1"); project = updateAssessmentScope(project, "E1", { level: "component", componentIds: [project.components[0].id] }); assert.deepEqual(getComponentRemovalImpact(project, project.components[0].id).orphanedAssessmentIds, ["E1"]); assert.equal(removeComponent(project, project.components[0].id, "cancel"), project); assert.equal(removeComponent(project, project.components[0].id, "convert-to-project").criteriaAssessments[0].scope.level, "project"); });
test("criterion and strategy actions preserve IDs", () => { let project = addCriterionAssessment(make(), "E1"); project = updateCriterionAssessment(project, "E1", { relevance: "high" }); project = addStrategy(project, "E1", { title: "Reduce", description: "", status: "selected", notes: "" }); const id = project.criteriaAssessments[0].strategies[0].id; project = updateStrategy(project, "E1", id, { title: "Reduce more" }); assert.equal(project.criteriaAssessments[0].strategies[0].id, id); project = removeStrategy(project, "E1", id); assert.equal(project.criteriaAssessments[0].strategies.length, 0); project = removeCriterionAssessment(project, "E1"); assert.equal(project.criteriaAssessments.length, 0); });
test("scope switches clear and restore component references", () => { let project = addComponent(make(), { name: "One", type: "other", description: "", notes: "" }); project = addCriterionAssessment(project, "E1"); const componentId = project.components[0].id; project = updateAssessmentScope(project, "E1", { level: "component", componentIds: [componentId] }); assert.equal(project.criteriaAssessments[0].scope.level, "component"); project = updateAssessmentScope(project, "E1", { level: "project", componentIds: [] }); assert.deepEqual(project.criteriaAssessments[0].scope.componentIds, []); });
test("selectors derive workspace summaries", () => { let project = addComponent(make(), { name: "One", type: "other", description: "", notes: "" }); project = addCriterionAssessment(project, "E1"); project = updateAssessmentScope(project, "E1", { level: "component", componentIds: [project.components[0].id] }); project = addStrategy(project, "E1", { title: "Reduce", description: "", status: "suggested", notes: "" }); assert.equal(selectComponentCount(project), 1); assert.equal(selectAssessmentCount(project), 1); assert.equal(selectStrategyCount(project), 1); assert.equal(selectUnreviewedAssessmentCount(project), 1); assert.equal(selectComponentReferenceCount(project, project.components[0].id), 1); assert.equal(selectAssessmentsByPillar(project).environment, 1); assert.equal(selectAssessmentsByStatus(project)["not-reviewed"], 1); });
