import { useMemo, useState, type FormEvent } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import {
  ASSESSMENT_RESPONSE_VALUES, CRITERION_RELEVANCE_VALUES, CRITERION_STATUS_VALUES, PROJECT_CRITERIA_BY_ID,
  PROJECT_CRITERIA_CATALOG, STRATEGY_STATUS_VALUES, type AssessmentResponse, type CriterionPillarId,
  type CriterionAssessment, type CriterionRelevance, type CriterionStatus, type ProjectStrategy, type StrategyStatus,
} from "../../../../../packages/standard-core/src/project";
import { Checkbox } from "@/components/ui/checkbox";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useWorkspace } from "./WorkspaceProvider";
import { dangerButton, fieldClass, humanize, primaryButton, secondaryButton } from "./ui";

type PillarFilter = "all" | CriterionPillarId;
const pillarStyles: Record<CriterionPillarId, string> = { environment: "border-l-[#28775e]", society: "border-l-[#a64545]", culture: "border-l-[#6b57a5]", finance: "border-l-[#b07918]" };

export function CriteriaView() {
  const workspace = useWorkspace(); const { project } = workspace; const [query, setQuery] = useState(""); const [pillar, setPillar] = useState<PillarFilter>("all"); const [selection, setSelection] = useState<"all" | "selected" | "not-selected">("all"); const [selectedId, setSelectedId] = useState<string | null>(project?.criteriaAssessments[0]?.criterionId ?? null); const [removeId, setRemoveId] = useState<string | null>(null);
  const filtered = useMemo(() => { const normalized = query.trim().toLowerCase(); const selected = new Set(project?.criteriaAssessments.map((item) => item.criterionId) ?? []); return PROJECT_CRITERIA_CATALOG.filter((item) => (pillar === "all" || item.pillarId === pillar) && (selection === "all" || (selection === "selected") === selected.has(item.id)) && (!normalized || `${item.id} ${item.label} ${item.summary} ${item.description}`.toLowerCase().includes(normalized))); }, [pillar, project?.criteriaAssessments, query, selection]);
  if (!project) return null;
  const definition = selectedId ? PROJECT_CRITERIA_BY_ID.get(selectedId) : undefined; const assessment = selectedId ? project.criteriaAssessments.find((item) => item.criterionId === selectedId) : undefined;
  const choose = (id: string) => setSelectedId(id);
  return <div><div><h2 className="text-3xl font-extrabold">Criteria</h2><p className="mt-2 text-sm leading-6 text-[#5f5a50]">Browse the canonical SD Standard library, then add project-specific scope, progress, strategies, and notes.</p></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(18rem,0.72fr)_minmax(26rem,1.28fr)]"><section aria-label="Criteria library"><div className="grid gap-3 rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-4"><label className="text-sm font-extrabold"><span className="inline-flex items-center gap-2"><Search className="h-4 w-4" />Search criteria</span><input className={fieldClass} placeholder="ID, title, or description" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1"><label className="text-sm font-extrabold">Pillar<select className={fieldClass} value={pillar} onChange={(event) => setPillar(event.target.value as PillarFilter)}><option value="all">All pillars</option><option value="environment">Environment</option><option value="society">Society</option><option value="culture">Culture</option><option value="finance">Finance</option></select></label><label className="text-sm font-extrabold">Selection<select className={fieldClass} value={selection} onChange={(event) => setSelection(event.target.value as typeof selection)}><option value="all">All criteria</option><option value="selected">Selected only</option><option value="not-selected">Not selected only</option></select></label></div></div><p className="mt-4 text-sm font-bold text-[#5f5a50]">{filtered.length} criteria</p><div className="mt-3 grid max-h-[65dvh] gap-3 overflow-y-auto pr-1">{filtered.map((item) => { const isSelected = project.criteriaAssessments.some((entry) => entry.criterionId === item.id); return <button className={`border-l-4 ${pillarStyles[item.pillarId]} rounded-md border-y border-r border-[#d9d4c8] bg-[#fffdf8] p-4 text-left transition hover:bg-white focus:outline-none focus:ring-4 focus:ring-[#85bba8] ${selectedId === item.id ? "ring-2 ring-[#28775e]" : ""}`} key={item.id} type="button" onClick={() => choose(item.id)}><span className="flex items-start justify-between gap-3"><span><strong>{item.displayId}: {item.label}</strong><span className="mt-1 block text-xs font-bold text-[#5f5a50]">{humanize(item.pillarId)}</span></span><span className="text-xs font-extrabold text-[#28775e]">{isSelected ? "Selected" : "Add"}</span></span><span className="mt-2 block text-sm leading-5 text-[#5f5a50]">{item.summary}</span></button>; })}</div></section>
      <section aria-live="polite" aria-label="Criterion assessment editor">{!definition ? <div className="rounded-md border border-dashed border-[#bbb5a8] p-10 text-center"><h3 className="text-xl font-extrabold">Select a criterion</h3><p className="mt-2 text-sm text-[#5f5a50]">Choose a criterion from the library to review or add it to the project.</p></div> : <div className="rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-5 sm:p-6"><div className={`border-l-4 ${pillarStyles[definition.pillarId]} pl-4`}><p className="text-sm font-extrabold text-[#5f5a50]">{definition.displayId} · {humanize(definition.pillarId)}</p><h3 className="mt-1 text-2xl font-extrabold">{definition.label}</h3><p className="mt-3 text-sm leading-6 text-[#5f5a50]">{definition.description}</p></div>{!assessment ? <div className="mt-6"><button className={primaryButton} type="button" onClick={() => workspace.addCriterionAssessment(definition.id)}><Plus className="h-4 w-4" />Add to project</button><p className="mt-3 text-sm text-[#5f5a50]">This starts as project-wide, unknown relevance, and not reviewed.</p></div> : <AssessmentEditor assessment={assessment} onRequestRemove={() => setRemoveId(assessment.criterionId)} />}</div>}</section></div>
    <AlertDialog open={removeId !== null} onOpenChange={(open) => { if (!open) setRemoveId(null); }}><AlertDialogContent className="border-[#d9d4c8] bg-[#fffdf8]"><AlertDialogHeader><AlertDialogTitle>Remove this project assessment?</AlertDialogTitle><AlertDialogDescription className="leading-6 text-[#5f5a50]">This removes its project-specific scope, relevance, progress, result, strategies, and notes. The criterion remains in the SD Standard library.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className="bg-[#8a3028] text-white" onClick={() => { if (removeId) workspace.removeCriterionAssessment(removeId); setRemoveId(null); }}>Remove assessment</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function AssessmentEditor({ assessment, onRequestRemove }: { assessment: CriterionAssessment; onRequestRemove: () => void }) {
  const workspace = useWorkspace(); const project = workspace.project!; const [scopeMessage, setScopeMessage] = useState("");
  const selectedComponentIds: string[] = assessment.scope.level === "component" ? assessment.scope.componentIds : [];
  const setScopeLevel = (level: "project" | "component") => { if (level === "project") { workspace.updateAssessmentScope(assessment.criterionId, { level: "project", componentIds: [] }); setScopeMessage(""); } else if (project.components.length === 0) setScopeMessage("Create a component before choosing component scope."); else { workspace.updateAssessmentScope(assessment.criterionId, { level: "component", componentIds: [project.components[0].id] }); setScopeMessage(""); } };
  const toggleComponent = (id: string, checked: boolean) => { if (assessment.scope.level !== "component") return; const next = checked ? Array.from(new Set([...assessment.scope.componentIds, id])) : assessment.scope.componentIds.filter((item) => item !== id); if (next.length === 0) { setScopeMessage("Component scope requires at least one component."); return; } workspace.updateAssessmentScope(assessment.criterionId, { level: "component", componentIds: next }); setScopeMessage(""); };
  return <div className="mt-7 grid gap-6"><fieldset><legend className="text-sm font-extrabold">Scope</legend><p className="mt-1 text-sm text-[#5f5a50]">Apply this assessment to the whole project or selected components.</p><div className="mt-3 flex flex-wrap gap-2"><button className={assessment.scope.level === "project" ? primaryButton : secondaryButton} type="button" onClick={() => setScopeLevel("project")}>Whole project</button><button className={assessment.scope.level === "component" ? primaryButton : secondaryButton} type="button" onClick={() => setScopeLevel("component")}>Selected components</button></div>{assessment.scope.level === "component" && <div className="mt-4 grid gap-2 sm:grid-cols-2">{project.components.map((component) => <label className="flex items-start gap-3 rounded-md border border-[#d9d4c8] p-3 text-sm font-bold" key={component.id}><Checkbox checked={selectedComponentIds.includes(component.id)} onCheckedChange={(value) => toggleComponent(component.id, value === true)} /><span>{component.name}</span></label>)}</div>}{scopeMessage && <p className="mt-3 text-sm font-bold text-[#8a3028]" role="alert">{scopeMessage}</p>}</fieldset>
    <div className="grid gap-5 md:grid-cols-3"><SelectField label="Relevance" help="How important is this criterion to the project?" value={assessment.relevance} values={CRITERION_RELEVANCE_VALUES} onChange={(value) => workspace.updateCriterionAssessment(assessment.criterionId, { relevance: value as CriterionRelevance })} /><SelectField label="Progress" help="Where are you in addressing this criterion?" value={assessment.status} values={CRITERION_STATUS_VALUES} onChange={(value) => workspace.updateCriterionAssessment(assessment.criterionId, { status: value as CriterionStatus })} /><SelectField label="Result level" help="How strongly has the project addressed this criterion so far?" value={assessment.response} values={ASSESSMENT_RESPONSE_VALUES} onChange={(value) => workspace.updateCriterionAssessment(assessment.criterionId, { response: value as AssessmentResponse })} /></div>
    <label className="text-sm font-extrabold">Assessment notes<textarea className={`${fieldClass} min-h-28`} value={assessment.notes} onChange={(event) => workspace.updateCriterionAssessment(assessment.criterionId, { notes: event.target.value })} /></label>
    <StrategiesEditor criterionId={assessment.criterionId} strategies={assessment.strategies} />
    <div className="border-t border-[#d9d4c8] pt-5"><button className={dangerButton} type="button" onClick={onRequestRemove}><Trash2 className="h-4 w-4" />Remove assessment</button></div>
  </div>;
}

function SelectField({ label, help, value, values, onChange }: { label: string; help: string; value: string; values: readonly string[]; onChange: (value: string) => void }) { return <label className="text-sm font-extrabold">{label}<span className="mt-1 block min-h-10 font-medium leading-5 text-[#5f5a50]">{help}</span><select className={fieldClass} value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label>; }

function StrategiesEditor({ criterionId, strategies }: { criterionId: string; strategies: ProjectStrategy[] }) {
  const workspace = useWorkspace(); const [adding, setAdding] = useState(false); const [title, setTitle] = useState("");
  const add = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; workspace.addStrategy(criterionId, { title: title.trim(), description: "", status: "suggested", notes: "" }); setTitle(""); setAdding(false); };
  return <section aria-labelledby="strategies-heading"><div className="flex items-center justify-between gap-3"><div><h4 id="strategies-heading" className="text-xl font-extrabold">Strategies</h4><p className="mt-1 text-sm text-[#5f5a50]">Record options, decisions, and trade-offs.</p></div><button className={secondaryButton} type="button" onClick={() => setAdding(true)}><Plus className="h-4 w-4" />Add strategy</button></div>{adding && <form className="mt-4 flex flex-col gap-3 rounded-md bg-[#e5efe9] p-4 sm:flex-row sm:items-end" onSubmit={add}><label className="flex-1 text-sm font-extrabold">Strategy title<input autoFocus required className={fieldClass} value={title} onChange={(event) => setTitle(event.target.value)} /></label><button className={primaryButton}>Add</button><button className={secondaryButton} type="button" onClick={() => setAdding(false)}>Cancel</button></form>}{strategies.length === 0 ? <p className="mt-4 rounded-md border border-dashed border-[#bbb5a8] p-5 text-sm text-[#5f5a50]">No strategies added yet.</p> : <div className="mt-4 grid gap-4">{strategies.map((strategy) => <article className="rounded-md border border-[#d9d4c8] bg-white p-4" key={strategy.id}><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_14rem]"><label className="text-sm font-extrabold">Title<input className={fieldClass} value={strategy.title} onChange={(event) => workspace.updateStrategy(criterionId, strategy.id, { title: event.target.value })} /></label><SelectField label="Status" help="Strategy decision and delivery state." value={strategy.status} values={STRATEGY_STATUS_VALUES} onChange={(value) => workspace.updateStrategy(criterionId, strategy.id, { status: value as StrategyStatus })} /></div><label className="mt-4 block text-sm font-extrabold">Description<textarea className={`${fieldClass} min-h-20`} value={strategy.description} onChange={(event) => workspace.updateStrategy(criterionId, strategy.id, { description: event.target.value })} /></label><label className="mt-4 block text-sm font-extrabold">Notes{strategy.status === "rejected" && <span className="ml-2 font-medium text-[#7a4b10]">Document why this option was rejected.</span>}<textarea className={`${fieldClass} min-h-20`} value={strategy.notes} onChange={(event) => workspace.updateStrategy(criterionId, strategy.id, { notes: event.target.value })} /></label><button className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold text-[#8a3028] underline decoration-2 underline-offset-4" type="button" onClick={() => workspace.removeStrategy(criterionId, strategy.id)}><Trash2 className="h-4 w-4" />Remove strategy</button></article>)}</div>}</section>;
}
