import { useState, type FormEvent } from "react";
import { FolderOpen, Plus } from "lucide-react";
import { PROJECT_STAGES, type ProjectStage } from "../../../../../packages/standard-core/src/project";
import { useWorkspace } from "./WorkspaceProvider";
import { fieldClass, primaryButton, secondaryButton } from "./ui";
import { humanize } from "./ui";

export function NoProjectState({ onOpen }: { onOpen: () => void }) {
  const { createNewProject, loadAbiertoExample } = useWorkspace();
  const [showForm, setShowForm] = useState(false);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [stage, setStage] = useState<ProjectStage>("planning"); const [types, setTypes] = useState("");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!title.trim()) return; createNewProject({ title: title.trim(), description, stage, projectTypes: types.split(",").map((item) => item.trim()).filter(Boolean) }); };
  return <main className="min-h-[70dvh] bg-[#f7f5ef] px-5 py-14 sm:px-8 lg:px-10"><div className="mx-auto max-w-3xl"><p className="text-sm font-extrabold text-[#28775e]">Project Workspace</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight sm:text-5xl">Start with one portable project</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#5f5a50]">Create a project here or open an SD Standard JSON file. Your work stays in this browser until you download a portable copy.</p>
    {!showForm ? <div className="mt-8 flex flex-wrap gap-3"><button className={primaryButton} type="button" onClick={() => setShowForm(true)}><Plus className="h-4 w-4" />Start a new project</button><button className={secondaryButton} type="button" onClick={onOpen}><FolderOpen className="h-4 w-4" />Open project JSON</button>{import.meta.env.DEV && <button className={secondaryButton} type="button" onClick={loadAbiertoExample}>Load Abierto example</button>}</div> : <form className="mt-8 grid gap-5 rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-6" onSubmit={submit}><h2 className="text-2xl font-extrabold">New project</h2><label className="text-sm font-extrabold">Project title<input autoFocus required className={fieldClass} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="text-sm font-extrabold">Description <span className="font-medium text-[#5f5a50]">(optional)</span><textarea className={`${fieldClass} min-h-28`} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-extrabold">Stage<select className={fieldClass} value={stage} onChange={(event) => setStage(event.target.value as ProjectStage)}>{PROJECT_STAGES.map((item) => <option key={item} value={item}>{item.split("-").join(" ")}</option>)}</select></label><label className="text-sm font-extrabold">Project types <span className="font-medium text-[#5f5a50]">(optional)</span><input className={fieldClass} placeholder="exhibition, print, website" value={types} onChange={(event) => setTypes(event.target.value)} /></label></div><div className="flex flex-wrap gap-3"><button className={primaryButton} type="submit">Create project</button><button className={secondaryButton} type="button" onClick={() => setShowForm(false)}>Cancel</button></div></form>}
  </div></main>;
}

export function InvalidLocalProjectState({ onOpen }: { onOpen: () => void }) {
  const { clearInvalidLocalData, loadAbiertoExample } = useWorkspace();
  return <main className="min-h-[70dvh] bg-[#f7f5ef] px-5 py-14 sm:px-8 lg:px-10"><div className="mx-auto max-w-3xl rounded-md border border-[#a33b32] bg-[#fff4f1] p-7"><h1 className="text-3xl font-extrabold text-[#7d261f]">The locally saved project is invalid</h1><p className="mt-4 leading-7 text-[#60231f]">It was not opened or replaced. Clear the invalid browser data, open a valid project file, or load the development fixture.</p><div className="mt-6 flex flex-wrap gap-3"><button className={primaryButton} type="button" onClick={clearInvalidLocalData}>Clear invalid local data</button><button className={secondaryButton} type="button" onClick={onOpen}>Open project JSON</button>{import.meta.env.DEV && <button className={secondaryButton} type="button" onClick={loadAbiertoExample}>Load Abierto example</button>}</div></div></main>;
}

export function ImportPreviewState({ onOpen, onConfirmed }: { onOpen: () => void; onConfirmed: () => void }) {
  const workspace = useWorkspace(); const preview = workspace.importPreview;
  if (!preview) return null;
  return <main className="min-h-[70dvh] bg-[#f7f5ef] px-5 py-14 sm:px-8 lg:px-10"><section className={`mx-auto max-w-3xl rounded-md border p-7 ${preview.success ? "border-[#28775e] bg-[#e5efe9]" : "border-[#a33b32] bg-[#fff4f1]"}`} tabIndex={-1}><p className="text-sm font-extrabold text-[#28775e]">Project Workspace</p><h1 className="mt-2 text-3xl font-extrabold">Import preview</h1>{preview.success ? <><p className="mt-3 text-sm leading-6 text-[#365146]">Review the project before saving it in this browser.</p><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="font-bold text-[#5f5a50]">Title</dt><dd className="font-extrabold">{preview.project.project.title}</dd></div><div><dt className="font-bold text-[#5f5a50]">Stage</dt><dd className="font-extrabold">{humanize(preview.project.project.stage)}</dd></div><div><dt className="font-bold text-[#5f5a50]">Components</dt><dd className="font-extrabold">{preview.project.components.length}</dd></div><div><dt className="font-bold text-[#5f5a50]">Criteria assessments</dt><dd className="font-extrabold">{preview.project.criteriaAssessments.length}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3"><button className={primaryButton} type="button" onClick={() => { if (workspace.confirmImport()) onConfirmed(); }}>Open project</button><button className={secondaryButton} type="button" onClick={workspace.cancelImport}>Cancel</button></div></> : <><p className="mt-3 font-bold text-[#60231f]">This file is invalid and cannot be opened.</p><ul className="mt-4 grid gap-2 text-sm text-[#60231f]">{preview.errors.map((error) => <li key={`${error.code}-${error.path}`}>{error.message}</li>)}</ul><div className="mt-6 flex flex-wrap gap-3"><button className={secondaryButton} type="button" onClick={onOpen}>Choose another file</button><button className={secondaryButton} type="button" onClick={workspace.cancelImport}>Cancel</button></div></>}</section></main>;
}
