import { useState } from "react";
import { Download, FolderOpen, Trash2 } from "lucide-react";
import { selectAssessmentCount, selectComponentCount, selectStrategyCount } from "../../../../../packages/standard-core/src/project";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { useWorkspace } from "./WorkspaceProvider";
import { dangerButton, downloadJson, formatDate, humanize, primaryButton, secondaryButton } from "./ui";

export function ProjectFileView({ onOpen, onImported }: { onOpen: () => void; onImported: () => void }) {
  const workspace = useWorkspace(); const { project, validation, importPreview } = workspace; const [clearMode, setClearMode] = useState<"clear" | "new" | "example" | null>(null); const [exportErrors, setExportErrors] = useState<string[]>([]);
  if (!project) return null;
  const download = () => { const result = workspace.exportCurrentProject(); if (!result.result) { setExportErrors(result.errors.map((item) => item.message)); return; } setExportErrors([]); downloadJson(result.result.json, result.result.filename); };
  const confirmImport = () => { if (workspace.confirmImport()) onImported(); };
  const details = [["Project title", project.project.title || "Untitled project"], ["Schema version", project.schema.version], ["Criteria version", project.standard.criteriaVersion], ["Stage", humanize(project.project.stage)], ["Components", String(selectComponentCount(project))], ["Criteria assessments", String(selectAssessmentCount(project))], ["Strategies", String(selectStrategyCount(project))], ["Last updated", formatDate(project.project.updatedAt)], ["Last export", formatDate(project.application.exportedAt)]];
  return <div><h2 className="text-3xl font-extrabold">Project File</h2><p className="mt-2 text-sm leading-6 text-[#5f5a50]">Validate, exchange, or remove the portable project saved in this browser.</p>
    <section className="mt-6 rounded-md border border-[#d9d4c8] bg-[#fffdf8] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-xl font-extrabold">File status</h3><p className={`mt-2 font-extrabold ${validation?.valid ? "text-[#28775e]" : "text-[#8a3028]"}`}>{validation?.valid ? "Valid project file" : `${validation?.errors.length ?? 0} blocking validation issues`}</p></div><div className="flex flex-wrap gap-3"><button className={primaryButton} type="button" onClick={download}><Download className="h-4 w-4" />Download project JSON</button><button className={secondaryButton} type="button" onClick={onOpen}><FolderOpen className="h-4 w-4" />Open project JSON</button></div></div>{exportErrors.length > 0 && <ul className="mt-4 rounded-md border border-[#a33b32] bg-[#fff4f1] p-4 text-sm text-[#60231f]" role="alert">{exportErrors.map((message) => <li key={message}>{message}</li>)}</ul>}<dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3">{details.map(([label, value]) => <div key={label}><dt className="font-bold text-[#5f5a50]">{label}</dt><dd className="mt-1 font-extrabold">{value}</dd></div>)}</dl></section>
    {importPreview && <section className={`mt-6 rounded-md border p-5 ${importPreview.success ? "border-[#28775e] bg-[#e5efe9]" : "border-[#a33b32] bg-[#fff4f1]"}`} tabIndex={-1}><h3 className="text-xl font-extrabold">Import preview</h3>{importPreview.success ? <><p className="mt-2 text-sm leading-6 text-[#365146]">Review this project before replacing the currently open local project.</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="font-bold text-[#5f5a50]">Title</dt><dd className="font-extrabold">{importPreview.project.project.title}</dd></div><div><dt className="font-bold text-[#5f5a50]">Stage</dt><dd className="font-extrabold">{humanize(importPreview.project.project.stage)}</dd></div><div><dt className="font-bold text-[#5f5a50]">Schema</dt><dd className="font-extrabold">{importPreview.project.schema.version}</dd></div><div><dt className="font-bold text-[#5f5a50]">Criteria version</dt><dd className="font-extrabold">{importPreview.project.standard.criteriaVersion}</dd></div><div><dt className="font-bold text-[#5f5a50]">Components</dt><dd className="font-extrabold">{importPreview.project.components.length}</dd></div><div><dt className="font-bold text-[#5f5a50]">Assessments / strategies</dt><dd className="font-extrabold">{importPreview.project.criteriaAssessments.length} / {selectStrategyCount(importPreview.project)}</dd></div></dl>{importPreview.warnings.length > 0 && <ul className="mt-4 text-sm text-[#7a4b10]">{importPreview.warnings.map((warning) => <li key={`${warning.code}-${warning.path}`}>{warning.message}</li>)}</ul>}<div className="mt-5 flex flex-wrap gap-3"><button className={primaryButton} type="button" onClick={confirmImport}>Replace current project</button><button className={secondaryButton} type="button" onClick={workspace.cancelImport}>Cancel</button></div></> : <><p className="mt-2 text-sm font-bold text-[#60231f]">This file is invalid. The current project has not changed.</p><ul className="mt-4 grid gap-2 text-sm text-[#60231f]">{importPreview.errors.map((error) => <li key={`${error.code}-${error.path}`}><strong>{error.path || "Project file"}:</strong> {error.message}</li>)}</ul><button className={`${secondaryButton} mt-5`} type="button" onClick={workspace.cancelImport}>Dismiss</button></>}</section>}
    <section className="mt-8 border-t border-[#d9d4c8] pt-6"><h3 className="text-xl font-extrabold">Local browser copy</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-[#5f5a50]">Clearing or starting over removes this project from this browser. Download a JSON copy first if you want to keep it.</p><div className="mt-5 flex flex-wrap gap-3"><button className={dangerButton} type="button" onClick={() => setClearMode("clear")}><Trash2 className="h-4 w-4" />Clear local project</button><button className={secondaryButton} type="button" onClick={() => setClearMode("new")}>Start new project</button>{import.meta.env.DEV && <button className={secondaryButton} type="button" onClick={() => setClearMode("example")}>Load Abierto example</button>}</div></section>
    <AlertDialog open={clearMode !== null} onOpenChange={(open) => { if (!open) setClearMode(null); }}><AlertDialogContent className="border-[#d9d4c8] bg-[#fffdf8]"><AlertDialogHeader><AlertDialogTitle>{clearMode === "example" ? "Replace with the Abierto example?" : clearMode === "new" ? "Start a new project?" : "Clear the local project?"}</AlertDialogTitle><AlertDialogDescription className="leading-6 text-[#5f5a50]">{clearMode === "example" ? "The current locally open project will be replaced by the development fixture." : "This removes the project saved in this browser. Download a JSON copy first if you want to keep it."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction className={clearMode === "example" ? "bg-[#28775e] text-white" : "bg-[#8a3028] text-white"} onClick={() => { if (clearMode === "example") { workspace.loadAbiertoExample(); onImported(); } else workspace.clearProject(); setClearMode(null); }}>{clearMode === "example" ? "Load example" : clearMode === "new" ? "Clear and start new" : "Clear local project"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
